#!/bin/bash
cd agent
export SKEP_APP_URL=http://localhost:5000/
export SKEP_CHARTS_URL=http://localhost:5040/
export SKEP_SECRET=abc123
export HOSTFS_PATH=linux_metrics/test_filesystem/
export LOG_LEVEL=debug
export SKEP_HOST=DOCKER-DESKTOP
export FILE_SYSTEMS=/
pipenv run python app.py
