#!/bin/bash
cd charts
export SKEP_APP_URL=http://localhost:60420/
export SKEP_CHARTS_URL=http://localhost:5040/
export SKEP_ENV=development
export FLASK_APP=controller.py
export FLASK_DEBUG=1
export SKEP_LISTEN_HOST=0.0.0.0
export SKEP_CHARTS_PORT=5040
export SKEP_CHARTS_DB_PATH=/tmp/charts.db
export SKEP_CHARTS_DB_PERSIST=1
export LOG_LEVEL=debug
pipenv run python app.py
