#!/bin/bash
cd app
export SKEP_ENV=development
export FLASK_APP=controller.py
export FLASK_DEBUG=1
export SKEP_LISTEN_HOST=0.0.0.0
export SKEP_CHARTS_URL=http://localhost:5040/
pipenv run gunicorn app -b 0.0.0.0:5000 \
                        -b 0.0.0.0:6666 \
                        --workers 1 \
                        --no-sendfile \
                        --worker-class eventlet
