#!/bin/bash
cd stats
export SKEP_APP_URL=http://localhost:5000/
export SKEP_SECRET=abc123
export HOSTFS_PATH=../linux-metrics/linux_metrics/test_filesystem/
export LOG_LEVEL=debug
export SKEP_HOST=DOCKER-DESKTOP
export FILE_SYSTEMS=/

../bin/python app.py
