#!/bin/sh
. /assets.sh
pipenv run gunicorn app -b 0.0.0.0:8080 \
                        -b 0.0.0.0:6666 \
                        --workers 1 \
                        --no-sendfile \
                        --worker-class eventlet
