#!/bin/sh
. /assets.sh
pipenv run gunicorn webapp --workers ${WEB_CONCURRENCY:-8} \
                           -b 0.0.0.0:8081 \
                           -k tornado \
                           --no-sendfile
